export const COMMON_DOG_BREEDS = [
  "Mixed Breed", "Labrador Retriever", "German Shepherd", "Golden Retriever", "French Bulldog", "Bulldog", "Poodle", "Beagle", "Rottweiler", "Dachshund", "Corgi", "Australian Shepherd", "Yorkshire Terrier", "Boxer", "Great Dane", "Siberian Husky", "Cavalier King Charles Spaniel", "Doberman Pinscher", "Shih Tzu", "Boston Terrier"
];

export const COMMON_CAT_BREEDS = [
  "Mixed Breed (Domestic Shorthair)", "Maine Coon", "Ragdoll", "Persian", "Siamese", "British Shorthair", "Abyssinian", "Sphynx", "Bengal", "Scottish Fold", "Russian Blue", "Siberian", "Birman", "Norwegian Forest Cat", "Oriental Shorthair", "Devon Rex", "Burmese", "Himalayan", "American Shorthair", "Turkish Angora"
];

export const MEDICAL_CONDITIONS = [
  "None",
  "Addison's Disease",
  "Anxiety / Stress",
  "Arthritis / Joint Issues",
  "Bad Breath (Halitosis)",
  "Bladder Stones",
  "Brachycephalic Syndrome",
  "Cancer",
  "Cognitive Dysfunction (Dementia)",
  "Constipation",
  "Cruciate Ligament Injury",
  "Cushing's Disease",
  "Dehydration Prone",
  "Dental Disease",
  "Diabetes",
  "Diarrhea (Chronic)",
  "Digestive Issues (IBD/IBS)",
  "Distemper History",
  "Ear Infections",
  "Feline Leukemia (FeLV)",
  "FIV",
  "Flea Allergy Dermatitis",
  "Food Allergies",
  "Gingivitis",
  "Glaucoma / Eye Issues",
  "Hairballs (Cats)",
  "Heart Disease",
  "Heartworm",
  "High Blood Pressure",
  "Hip Dysplasia",
  "Hyperthyroidism (Cats)",
  "Hypothyroidism (Dogs)",
  "Kennel Cough",
  "Kidney Disease (Renal Failure)",
  "Liver Disease",
  "Lyme Disease",
  "Mange",
  "Megacolon",
  "Obesity / Overweight",
  "Pancreatitis",
  "Parvovirus History",
  "Patellar Luxation",
  "Periodontal Disease",
  "Pyometra",
  "Seizures / Epilepsy",
  "Sensitive Stomach",
  "Skin Infections / Hot Spots",
  "Underweight",
  "Urinary Tract Issues (FLUTD/Struvite)",
  "Vomiting (Chronic)"
];

export const FOOD_BRANDS = [
  "Prescription Foods",
  "Non-Prescription Foods",
  "Generic / No Preference",
  "Acana",
  "Almo Nature",
  "American Journey",
  "Annamaet",
  "Applaws",
  "Authority",
  "Blue Buffalo",
  "Canidae",
  "Castor & Pollux",
  "Crave",
  "Diamond Naturals",
  "Dr. Tim's",
  "Eagle Pack",
  "Earthborn Holistic",
  "Eukanuba",
  "Fancy Feast",
  "Farmina",
  "Friskies",
  "Fromm",
  "Hill's Science Diet",
  "Honest Kitchen",
  "Iams",
  "Instinct",
  "Meow Mix",
  "Merrick",
  "Natural Balance",
  "Nulo",
  "Nutro",
  "Open Farm",
  "Orijen",
  "Pedigree",
  "Primal",
  "Purina Pro Plan",
  "Rachael Ray Nutrish",
  "Royal Canin",
  "Sheba",
  "Simply Nourish",
  "Solid Gold",
  "SportDogFood",
  "Stella & Chewy's",
  "Taste of the Wild",
  "Tiki Cat",
  "Victor",
  "Wellness",
  "Weruva",
  "Whiskas",
  "Whole Earth Farms",
  "Ziture",
  "Ziwi Peak"
];